[versions]
agp = "8.6.1"
kotlin = "1.9.25"
coreKtx = "1.13.1"
kotpref = "2.13.2"
mavenPublish = "0.25.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotpref = { module = "com.chibatching.kotpref:kotpref", version.ref = "kotpref" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
